routes/web.php
<?php
use App\Http\Controllers\index2Controller;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', 'WelcomeController@index');

Route::get('/', 'WelcomeController@index');
Route::get('/Accuielle', 'index2controler@index');
Route::get('/Contact', 'ContactController@index');
Route::get('/About', 'AboutController@index');
Route::get('/Blog','BlogController@index');
Route::get('/News','NewsController@index');
Route::get('/Blogd','BlogDetaillController@index');
//Route::get('Accuielle',[index2controler::class, 'index']);
Route::resource('/categories', 'CategoriesController');
  Route::resource('/tags', 'TagsController');
  Route::resource('/posts', 'PostsController');
  
  Route::get('/import','PostsController@importForm');
 // Route::resource('/importPost','PostsController@import');
  Route::post('importPost','PostsController@import')->name('import');



Auth::routes();

Route::group(['middleware' => 'auth'], function() {

  Route::get('/home', 'HomeController@index')->name('home');
  
  
  Route::get('/trashed-posts', 'PostsController@trashed')->name('trashed.index');
  Route::get('/trashed-posts/{id}', 'PostsController@restore')->name('trashed.restore');
  Route::get('/postee/pdf', 'PostsController@createPDF');

});

Route::middleware(['auth', 'admin'])->group(function() {
  Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
  Route::get('/users', 'UsersController@index')->name('users.index');
  Route::post('/users/{user}/make-admin', 'UsersController@makeAdmin')->name('users.make-admin');
});

Route::middleware(['auth'])->group(function() {
  Route::get('/users/{user}/profile', 'UsersController@edit')->name('users.edit');
  Route::post('/users/{user}/profile', 'UsersController@update')->name('users.update');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Category;
use App\Tag;
use App\User;

class Post extends Model
{
  use SoftDeletes;

  protected $fillable = ['title', 'description', 'content', 'image', 'category_id','user_id'];

  public function category() {
    return $this->belongsTo(Category::class);
  }

  public function tags() {
    return $this->belongsToMany(Tag::class);
  }

  public function hasTag($tagId) {
    return in_array($tagId, $this->tags->pluck('id')->toArray());
  }

  public function user() {
    return $this->belongsTo(User::class);
  }


}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;
use App\Http\Requests\PostRequest;
use App\Http\Requests\UpdatePostRequest;
use Illuminate\Support\Facades\Storage;
use PDF;
use Excel;
use App\Imports\PosteImport;

class PostsController extends Controller
{

  public function __construct() {
    $this->middleware('checkCategory')->only('create');
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    return view('posts.index')->with('posts', Post::all());
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(PostRequest $request)
  {
    $post = Post::create([
      'title' => $request->title,
      'description' => $request->description,
      'content' => $request->content,
      'image' => $request->image->store('images', 'public'),
      'category_id' => $request->categoryID,
      'user_id' => $request->user_id
    ]);

    if ($request->tags) {
      $post->tags()->attach($request->tags);
    }

    session()->flash('success', 'post created successfully');
    return redirect(route('posts.index'));
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Post $post)
  {
    $user = $post->user;
    $profile = $user->profile;
    return view("posts.show")->with('post',$post)->with('categories',Category::all())->with('profile',$profile)->with('user',$user);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Post $post)
  {
    return view('posts.create', ['post' => $post, 'categories' => Category::all(), 'tags' => Tag::all()]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(UpdatePostRequest $request,Post $post)
  {

    $data = $request->only(['title', 'description', 'content']);
    if ($request->hasFile('image')) {
      $image = $request->image->store('images', 'public');
      Storage::disk('public')->delete($post->image);
      $data['image'] = $image;
    }

    if ($request->tags) {
      $post->tags()->sync($request->tags);
    }

    $post->update($data);

    session()->flash('success', 'post updated successfully');
    return redirect(route('posts.index'));
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
      $post = Post::withTrashed()->where('id', $id)->first();
      if ($post->trashed()) {
          Storage::disk('public')->delete($post->image);
          $post->forceDelete();
      } else {
          $post->delete();
      }
      session()->flash('success', 'post trashed successfully');
      return redirect(route('posts.index'));
  }

  public function trashed() {
      $trashed = Post::onlyTrashed()->get();
      return view('posts.index')->withPosts($trashed);
  }

  public function restore($id) {
    Post::withTrashed()->where('id', $id)->restore();
    session()->flash('success', 'post restored successfully');
    return redirect(route('posts.index'));
  }



  public function createPDF($request,Post $post) {
    // retreive all records from db
     $data = Post::all();
    // Post::select('image')->where('ID_PROCESSO', '123456')->get();
 //   $data = $request->only(['title', 'description', 'content'])-get();

    // share data to view
    view()->share('post',$data);
    $pdf = PDF::loadView('about', $data);

    // download PDF file with download method
    return $pdf->download('pdf_file.pdf');
  }



          public function importForm(){
            return view ('posts.import');
          }

          public function import(Request $request){
            Excel::import(new PosteImport,$request->file);
            return view ('posts.index')->with('posts', Post::all());          }

}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('stylesheets')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
@endsection
@section('content')
    <div class="card card-default">
        <div class="card-header">
            {{ isset($post) ? "Update Post" : "Add a new Post" }}
        </div>
        <div class="card-body">
        <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                @if (isset($post))
                  @method('PUT')
                @endif
                <div class="form-group">
                    <label for="post title">Title:</label>
                <input type="text" class="form-control" name="title" placeholder="Add a new post" value="{{ isset($post) ? $post->title : "" }}">
                </div>
                <div class="form-group">
                    <label for="post description">Description:</label>
                    <textarea class="form-control" rows="2" name="description" placeholder="Add a description">{{ isset($post) ? $post->description : "" }}</textarea>
                </div>
                <div class="form-group">
                    <label for="post content">content:</label>
                    {{-- <textarea class="form-control" rows="3" name="content" placeholder="Add a content"></textarea> --}}
                    <input id="x" type="hidden" name="content" value="{{ isset($post) ? $post->content : "" }}">
                    <trix-editor input="x"></trix-editor>
                </div>
                @if (isset($post))
                  <div class="form-group">
                    <img src="{{asset('storage/' . $post->image)}}" style="width: 100%" />
                  </div>
                @endif
                <div class="form-group">
                    <label for="post image">Image:</label>
                    <input type="file" class="form-control" name="image">
                </div>
                <div class="form-group">
                  <label for="selectCategory">Select a category</label>
                  <select name="categoryID" class="form-control" id="selectCategory">
                    @foreach ($categories as $category)
                      <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                  </select>
                </div>
                @if (!$tags->count() <= 0 && isset($post))
                  <div class="form-group">
                    <label for="selectTag">Select a tag</label>
                    <select name="tags[]" class="form-control tags" id="selectTag" multiple>
                      @foreach ($tags as $tag)
                        <option value="{{$tag->id}}"
                          @if ($post->hasTag($tag->id))
                            selected
                          @endif
                          >
                          {{$tag->name}}
                        </option>
                      @endforeach
                    </select>
                  </div>
                @endif
                <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                <div class="form-group">
                    <button type="submit" class="btn btn-success">
                        {{ isset($post) ? "Update" : "Add" }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script>
      $(document).ready(function() {
        $('.tags').select2();
      });
    </script>
@endsection

resources/views/posts/import.blade.php
@extends('layouts.app')

@section('content')

            <div class="container">
            <div class="row">
            <div class="col-md-6 offset-md-3">
          

        <div class="card-body">
            <form   
            action="{{ route('import') }}"
             method="POST" 
               enctype="multipart/form-data">

               
               @csrf
                @method('POST')
                <input type="file" name="file" class="form-control">
                <br>
                <button class="btn btn-success">Import File</button>
            </form>
        </div>




            </div>
            </div>
            </div>




@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    <script>
      $(document).ready(function() {
        $('.tags').select2();
      });
    </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
@if(Auth::user()->isAdmin())
  <div class="clearfix">
    <a href="{{ route('posts.create') }}"
    class="btn float-right btn-success"
    style="margin-bottom: 10px">
      Add Post
    </a>
  </div>
  <div class="card card-default">
    <div class="card-header">All Posts</div>
        @if ($posts->count() > 0)


        <div class="clearfix">
            <form   
            action="{{ route('import') }}"
             method="POST" 
               enctype="multipart/form-data">

               
               @csrf
                @method('POST')
                <input type="file" name="file" class="form-control">
                <br>
                <button class="btn btn-success">Import File</button>
            </form>
        </div>


          <table class="card-body">
            <table class="table">
              <thead>
                <tr>
                <th>Download</th>
                  <th>Image</th>
                  <th>Title</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($posts as $post)
                  <tr>
                  <td>
                  <a href="storage/{{$post->image}}" class="btn btn-secondary" download="{{$post->image}}">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-bar-down"
                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" 
                       d="M1 3.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5zM8 6a.5.5 
                       0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 
                       .708-.708L7.5 12.293V6.5A.5.5 0 0 1 8 6z"/>
                       </svg>
</a>
</td>
                    <td>
                      <img src="{{ asset('storage/'.$post->image) }}" alt="" width="100px" height="50px">
                    </td>
                    <td>
                      {{ $post->title }}
                    </td>
                    <td>
                      <form class="float-right ml-2"
                      action="{{route('posts.destroy', $post->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                          <button class="btn btn-danger btn-sm">
                            {{ $post->trashed() ? 'Delete' : 'Trash' }}
                        </button>
                      </form>
                      @if (!$post->trashed())
                        <a href="{{route('posts.edit', $post->id)}}" class="btn btn-primary float-right btn-sm">Edit</a>
                      @else
                        <a href="{{route('trashed.restore', $post->id)}}" class="btn btn-primary float-right btn-sm">Restore</a>
                      @endif
                    </td>
                  </tr>
                @endforeach
              </tbody>
          </table>
        @else
          <div class="card-body">
            <h1 class="text-center">
              No Posts Yet.
            </h1>
          </div>
        @endif
    </div>
  </div>
  @endif
@endsection

resources/views/posts/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
  <meta name="description" content="Mobile Application HTML5 Template">

  <meta name="copyright" content="MACode ID, https://www.macodeid.com/">

  <title>Mobster - One page app template</title>

  <link rel="shortcut icon" href="../assets/favicon.png" type="image/x-icon">

  <link rel="stylesheet" href="../assets/css/maicons.css">

  <link rel="stylesheet" href="../assets/vendor/animate/animate.css">

  <link rel="stylesheet" href="../assets/vendor/owl-carousel/css/owl.carousel.min.css">

  <link rel="stylesheet" href="../assets/css/bootstrap.css">

  <link rel="stylesheet" href="../assets/css/mobster.css">

</head>
<body>
@extends('navbar.app2')
<div class="page-hero-section bg-image hero-home-1" style="background-image: url(../assets/img/bg_hero_1.svg);">



  <section class="hero-wrap hero-wrap-2 js-fullheight" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread"></h1>
            <p class="breadcrumbs">
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="hero-wrap hero-wrap-2 js-fullheight" >
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-md-9 ftco-animate pb-5 text-center">
          <h1 class="mb-3 bread"></h1>
            <p class="breadcrumbs">
            </p>
          </div>
        </div>
      </div>
    </section>



   <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
        {!! $post->title !!}
          <div class="col-lg-8 ftco-animate">
            {!! $post->content !!}
            {!! $post->description !!}
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                @foreach ($post->tags as $tag)
                <a href="#" class="tag-cloud-link">{{ $tag->name }}</a>
                @endforeach
              </div>
            </div>
            <div class="ml-auto my-2 my-lg-0">
      

<a href="{{ asset('storage/'.$post->image) }}" class="btn btn-dark rounded-pill" download="{{$post->image}}">
Download
</a>
       
      </div>
          


           

          </div> <!-- .col-md-8 -->
          

        </div>
      </div>
    </section> <!-- .section -->
    </div>
    <div class="page-section mt-5">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-lg-3 py-3 wow zoomIn">
        <div class="img-place client-img">
          <img src="../assets/img/clients/alter_sport.png" alt="">
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-3 wow zoomIn">
        <div class="img-place client-img">
          <img src="../assets/img/clients/cleaning_service.png" alt="">
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-3 wow zoomIn">
        <div class="img-place client-img">
          <img src="../assets/img/clients/creative_photo.png" alt="">
        </div>
      </div>
      <div class="col-sm-6 col-lg-3 py-3 wow zoomIn">
        <div class="img-place client-img">
          <img src="../assets/img/clients/global_tv.png" alt="">
        </div>
      </div>
    </div>
  </div>
</div>
    <footer class="ftco-footer ftco-bg-dark ftco-section">
   
    <div class="page-footer-section bg-dark fg-white">
  <div class="container">
    <div class="row mb-5 py-3">
      <div class="col-sm-6 col-lg-2 py-3">
        <h5 class="mb-3">Pages</h5>
        <ul class="menu-link">
          <li><a href="#" class="">Features</a></li>
          <li><a href="#" class="">Customers</a></li>
          <li><a href="#" class="">Pricing</a></li>
          <li><a href="#" class="">GDPR</a></li>
        </ul>
      </div>
      <div class="col-sm-6 col-lg-2 py-3">
        <h5 class="mb-3">Company</h5>
        <ul class="menu-link">
          <li><a href="#" class="">About</a></li>
          <li><a href="#" class="">Team</a></li>
          <li><a href="#" class="">Leadership</a></li>
          <li><a href="#" class="">Careers</a></li>
          <li><a href="#" class="">HIRING!</a></li>
        </ul>
      </div>
      <div class="col-md-6 col-lg-4 py-3">
        <h5 class="mb-3">Contact</h5>
        <ul class="menu-link">
          <li><a href="#" class="">Contact Us</a></li>
          <li><a href="#" class="">Office Location</a></li>
          <li><a href="#" class="">hello@mobster.com</a></li>
          <li><a href="#" class="">support@macodeid.com</a></li>
          <li><a href="#" class="">+808 11233 900</a></li>
        </ul>
      </div>
      <div class="col-md-6 col-lg-4 py-3">
        <h5 class="mb-3">Subscribe</h5>
        <p>Get some offers, news, or update features of application</p>
        <form method="POST">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Your email..">
            <div class="input-group-append">
              <button type="submit" class="btn btn-primary"><span class="mai-send"></span></button>
            </div>
          </div>
        </form>

        <!-- Social Media Button -->
        <div class="mt-4">
          <a href="#" class="btn btn-fab btn-primary fg-white"><span class="mai-logo-facebook"></span></a>
          <a href="#" class="btn btn-fab btn-primary fg-white"><span class="mai-logo-twitter"></span></a>
          <a href="#" class="btn btn-fab btn-primary fg-white"><span class="mai-logo-instagram"></span></a>
          <a href="#" class="btn btn-fab btn-primary fg-white"><span class="mai-logo-google"></span></a>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 py-2">
        <img src="../assets/favicon-light.png" alt="" width="40">
        <!-- Please don't remove or modify the credits below -->
        <p class="d-inline-block ml-2">Copyright &copy; <a href="https://www.macodeid.com/" class="fg-white fw-medium">MACode ID</a>. All rights reserved</p>
      </div>
      <div class="col-12 col-md-6 py-2">
        <ul class="nav justify-content-end">
          <li class="nav-item"><a href="#" class="nav-link">Terms of Use</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Privacy Policy</a></li>
          <li class="nav-item"><a href="#" class="nav-link">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>




    </footer>

    <script src="../assets/js/jquery-3.5.1.min.js"></script>

<script src="../assets/js/bootstrap.bundle.min.js"></script>

<script src="../assets/vendor/owl-carousel/js/owl.carousel.min.js"></script>

<script src="../assets/vendor/wow/wow.min.js"></script>

<script src="../assets/js/mobster.js"></script>

  <!-- loader -->


 

  </body>
</html>